# Generated by Django 3.1.2 on 2020-10-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_vegan'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/media/images/n', upload_to='images/'),
            preserve_default=False,
        ),
    ]
